default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: e-bike-trading_development

test:
  <<: *default
  database: e-bike-trading_test

production:
  <<: *default
  database: e-bike-trading_production
  username: e-bike-trading
  password: <%= ENV['E-BIKE-TRADING_DATABASE_PASSWORD'] %>
